### ISSUE TITLE
does it support FlashAttention-2?

### ISSUE THREAD

**Issue by ericxsun** [SkyworkAI/Skywork#23]

**Comment by zhao1iang** [comment]
Yes, of course our model structure has not modified the attention part, so it can use flash attention v2. Because flash attention has stricter requirements on the environment, we did not use flash attention in the default configuration. If you need, you can refer to https://huggingface.co/togethercomputer/LLaMA-2-7B-32K/blob/main/modeling_flash_llama.py to directly adapt flash attention by modifying model_skywork.py, or you can use flash attention by adding patches similar to this project, https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/training/flash_attn_patch.py.
